CREATE TABLE evaluacion.estamento
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10 ),
    descripcion character varying(50) NOT NULL,
    porcentaje_peso numeric(4, 1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS evaluacion.tipo_evaluacion
    ADD COLUMN tev_estamento integer;
ALTER TABLE IF EXISTS evaluacion.tipo_evaluacion
    ADD CONSTRAINT fk_tipo_evaluacion_estamento FOREIGN KEY (tev_estamento)
    REFERENCES evaluacion.estamento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

INSERT INTO evaluacion.estamento(id, descripcion, porcentaje_peso)
VALUES
(10, 'Autoevaluación', '25.0'),
(11, 'Estudiantes', '25.0'),
(12, 'Talento Humano', '25.0'),
(13, 'Dirección Académica', '25.0');

UPDATE evaluacion.tipo_evaluacion SET tev_estamento = 10 WHERE tev_nombre LIKE 'AUTO%';
UPDATE evaluacion.tipo_evaluacion SET tev_estamento = 11 WHERE tev_nombre LIKE '%ESTUDIANTES';
UPDATE evaluacion.tipo_evaluacion SET tev_estamento = 12 WHERE tev_nombre LIKE '%HUMANO';
UPDATE evaluacion.tipo_evaluacion SET tev_estamento = 13 WHERE tev_nombre LIKE '%ACADEMICA';